### ISSUE TITLE
No software license included in repository

### ISSUE THREAD

**Issue by rlittlefield** [pohmelie/aiorequests#1]
Even though this library is short and sweet, it is lacking a license. Any plans to include one?

**Comment by pohmelie** [comment]
License described in [setup.py](https://github.com/pohmelie/aiorequests/blob/master/setup.py#L36). Or you mean to add it to readme?

**Comment by rlittlefield** [comment]
Ah, I didn't see that there. Adding it to the readme or a separate file would be helpful though.
